# LiveKit SIP Service Configuration
# MONKHUB INNOVATIONS PRIVATE LIMITED SIP Provider
# Mumbai Circle - Cloud SIP with INT-PHONY

log_level: debug
log_requests: true

api_key: 108378f337bbab3ce4e944554bed555a
api_secret: 2098a695dcf3b99b4737cca8034b122fb86ca9f904c13be1089181c0acb7932d
ws_url: ws://localhost:7880  # Will be overridden by LIVEKIT_WS_URL env var in Azure

redis:
  address: localhost:6379  # Will be overridden by REDIS_URL env var in Azure
  username: ""
  password: ""
  db: 0

# SIP Configuration for MONKHUB provider
sip_port: 5170
bind_address: "0.0.0.0"  # Listen on all interfaces
external_ip: "40.81.229.194"  # Azure public IP for SIP provider

health_port: 8080  # Match Azure health check expectations
prometheus_port: 9090  # Standard port for metrics

# RTP Configuration (as per provider: 6000-65531)
rtp_port: 6000-65531
rtp_bind_address: "0.0.0.0"

# Audio configuration for MONKHUB (G711 Alaw only)
audio:
  sample_rate: 8000
  channels: 1
  
# Timeouts and limits
timeout:
  sip_registration: 30s
  call_setup: 60s
  
max_concurrent_calls: 10  # Match your 10 channels

# Security settings
security:
  enable_authentication: true
  max_call_duration: 3600s  # 1 hour max call

# SIP Provider: MONKHUB INNOVATIONS
# Customer IP: 40.81.229.194
# SBC IP: 27.107.220.6
# TSI: INT-MU-SBC06-9345
# DEL No: 9240908080
# Username: 00919240908080
# Password: 1234
# Channels: 10
# Audio Codec: G711 Alaw only