# LiveKit SIP Service Configuration
# MONKHUB INNOVATIONS PRIVATE LIMITED SIP Provider
# Mumbai Circle - Cloud SIP with INT-PHONY

log_level: debug
log_requests: true

api_key: API5DcPxqyBDHLr
api_secret: b9dgi6VEHsXf1zLKFWffHONECta5Xvfs5ejgdZhUoxPE
ws_url: ws://localhost:7880

redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0

# SIP Configuration for MONKHUB provider
sip_port: 5170
bind_address: "0.0.0.0"  # Listen on all interfaces
external_ip: "0.0.0.0"  # Use all interfaces for testing

health_port: 8081  # Changed to avoid conflict
prometheus_port: 9091  # Changed to avoid conflict

# RTP Configuration (as per provider: 6000-65531)
rtp_port: 6000-65531
rtp_bind_address: "0.0.0.0"

# Audio configuration for MONKHUB (G711 Alaw only)
audio:
  sample_rate: 8000
  channels: 1
  
# Timeouts and limits
timeout:
  sip_registration: 30s
  call_setup: 60s
  
max_concurrent_calls: 10  # Match your 10 channels

# Security settings
security:
  enable_authentication: true
  max_call_duration: 3600s  # 1 hour max call

# SIP Provider: MONKHUB INNOVATIONS
# Customer IP: 40.81.229.194
# SBC IP: 27.107.220.6
# TSI: INT-MU-SBC06-9345
# DEL No: 9240908080
# Username: 00919240908080
# Password: 1234
# Channels: 10
# Audio Codec: G711 Alaw only