# LiveKit Server Configuration - Corrected Schema
port: 7880

redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0

# API Keys
keys:
  API5DcPxqyBDHLr: b9dgi6VEHsXf1zLKFWffHONECta5Xvfs5ejgdZhUoxPE

# RTC Configuration - Fixed for Azure deployment
rtc:
  port_range_start: 50000 
  port_range_end: 60000
  use_external_ip: true

# Production settings
log_level: info
development: false

# Room settings for SIP integration
room:
  auto_create: true