# LiveKit Server Configuration - Corrected Schema
port: 7880

redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0

# API Keys
keys:
  108378f337bbab3ce4e944554bed555a: 2098a695dcf3b99b4737cca8034b122fb86ca9f904c13be1089181c0acb7932d

# RTC Configuration - Fixed for Azure deployment
rtc:
  port_range_start: 50000 
  port_range_end: 60000
  use_external_ip: true

# Production settings
log_level: info
development: false

# Room settings for SIP integration
room:
  auto_create: true